#!/usr/bin/env bash

# My custom HLWM (HerbstluftWM) configuration file.

# Creating a function that shortens the "herbstclient" command to just "hc"
hc() {
    herbstclient "$@"
}

# AUTOSTART #
#-----------#
hc emit_hook reload
hc unlock
xsetroot -cursor_name left_ptr
turnstile-update-runit-env DISPLAY XAUTHORITY DBUS_SESSION_BUS_ADDRESS
pactl load-module module-switch-on-connect
pgrep -x sxhkd || sxhkd -c ~/.config/herbstluftwm/sxhkd/sxhkdrc &
hc keyunbind --all
nitrogen --restore &
picom -b
/usr/lib/xfce-polkit/xfce-polkit &

# KEYBINDINGS #
#-------------#
Mod=Mod4

tag_names=( {1..9} )
tag_keys=( {1..9} )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" chain , move_index "$i" , use_index "$i"
    fi
done

# CYCLE THROUGH TAGS #
#--------------------#
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# GENERAL SETTINGS #
#------------------#
hc set window_gap 6
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0
hc set focus_follows_mouse false
hc set smart_window_surroundings false

# THEME (elimininating window borders and titlebars) #
#----------------------------------------------------#
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222cc'
hc set frame_border_normal_color '#101010cc'
hc set frame_bg_normal_color '#565656aa'
hc set frame_bg_active_color '#345F0Caa'
hc set frame_border_width 0
hc set show_frame_decorations none
hc set frame_bg_transparent off
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.title_height 0
hc attr theme.title_when always
hc attr theme.title_font 'Dejavu Sans:pixelsize=12'  # example using Xft
hc attr theme.title_depth 3  # space below the title's baseline
hc attr theme.active.color '#345F0Cef'
hc attr theme.title_color '#ffffff'
hc attr theme.normal.color '#323232dd'
hc attr theme.urgent.color '#7811A1dd'
hc attr theme.tab_color '#1F1F1Fdd'
hc attr theme.active.tab_color '#2B4F0Add'
hc attr theme.active.tab_outer_color '#6C8257dd'
hc attr theme.active.tab_title_color '#ababab'
hc attr theme.normal.title_color '#898989'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 0
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#789161'
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color '#606060'

# Copy inner color to outer_color #
#---------------------------------#
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color '#141414'

# WINDOW RULES #
#--------------#

## GENERAL WINDOW RULES ##
hc unrule -F
hc rule focus=on
ruleopts="focus=on switchtag=on"
hc rule class=Firefox tag=1 $ruleopts
hc rule class=obsidian tag=3 $ruleopts
hc rule class=DrRacket tag=4 $ruleopts
hc rule class=org-nlogo-app-App tag=4 $ruleopts
hc rule class=Virt-manager tag=5 $ruleopts
hc rule class=kwave tag=6 $ruleopts
hc rule class=Gimp-2.99 tag=7 $ruleopts
hc rule class=Screenkey manage=off
hc rule class=Yad floating=on focus=on floatplacement=none

## SCRATCHPAD WINDOW RULES ##
scratchopts="focus=on floating=on floating_geometry=1500x900 floatplacement=center"
hc rule class=terminal $scratchopts
hc rule class=fm $scratchopts
hc rule class=music $scratchopts
hc rule class=bluetooth $scratchopts
hc rule class=email $scratchopts
hc rule class=Easytag $scratchopts

## SPECIAL WINDOW RULES ##
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on floatplacement=center
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floatplacement=center
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# USING POLYBAR #
#---------------#
panel=~/.scripts/launch-polybar
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
